### ISSUE TITLE
Is it possible to make 1 request every 2 seconds? 

### ISSUE THREAD

**Issue by abhsrivastava** [vercel/async-sema#50]
I am using the simple implementation RateLimiter and I am using the lowest value of 1 (1 request / sec) but I still get 500 errors from the server which I am calling. so I wonder if its possible to further reduce the number of calls say 1 every 2 seconds?

**Comment by OlliV** [comment]
If I recall correctly the following would do what you are asking:

```js
RateLimit(1, {
  timeUnit = 2000,
  uniformDistribution = false,
})
```
